# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.cache/wt [current_project]
set_property parent.project_path D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files d:/vivado_projects/54-single-cycle-CPU-design/coe-files/mips_54_mars_simulate_student_ForWeb.coe
add_files -quiet d:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/ext16.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/ext18.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/cp0.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/MULTU.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/HILOreg.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/clz.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/ctrl.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/join_instr.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/instr_decode.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/ext5.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/mux32_1.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/add8.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/regfile.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/add.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/DIVU.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/npc.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/alu.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/mux32_4.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/mux32_2.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/mux32_3.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/pcreg.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/MUL.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/mux5_1.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/mux5_2.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/mux32.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/DIV.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/cpu.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/Divider.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/dram.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/seg7x16.v
  D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/sources_1/imports/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/constrs_1/imports/new/cpu31.xdc
set_property used_in_implementation false [get_files D:/vivado_projects/54-single-cycle-CPU-design/CPU54-xb/CPU54-xb.srcs/constrs_1/imports/new/cpu31.xdc]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
